### PR TITLE
Added A Logo

### PR DESCRIPTION
**Pull request by ghost**
Hi
I just felt that the site lags a logo and I have made a simple yet meaningful logo. Please check it out.

### CODE REVIEW

**Comment by KevinWorkman** [comment]
Hey this is really great! Do you mind moving the file to somewhere in the `images` directory of this repo? Maybe give it a more descriptive name like `geekslider-logo.png` or something.

**Comment by ghost** [comment]
Done 👍

**Comment by KevinWorkman** [comment]
Hey sorry to be annoying, but I meant can you move the file into the `images` directory and then reference it by a relative URL? That way we don't have an external dependency (in case you delete your repo or something in the future).

I think the URL should be something like this:

    Happy Coding logo

**Comment by ghost** [comment]
HI sir absolutely sorry about that . That was my mistake; I am a bit new to github and I am a Engineering student from India. I just liked the way you are contributing to Github outside your work schedule. Even I dream to be a security engineer with Google once. I have already contributed to the security of Google, MS and other big sites.

**Comment by ghost** [comment]
wow. You are the same person from stackoverflow who once commented on one of my questions "How to find out original github page for any custom domain?". I feel really nice to meet you. -Ronnie

**Comment by KevinWorkman** [comment]
No worries, I'm still learning about git myself. Nice to meet you!

**Pull request merged**
