### PR TITLE
p5js tutorials link accessibility

### PR DESCRIPTION
**Pull request by arnoldboy123**
Improve the link accessibility and corrected some typos in the p5.js tutorial series

### CODE REVIEW

**Comment by arnoldboy123** [comment]
I am not really sure why there are conflicting files as I don't think I have added that as part of my commit.

**Comment by KevinWorkman** [comment]
I think a lot of these commits are from previous pull requests that have already been merged in. I think what you want to do is rebase your branch so that the diffs are against the latest changes in the repo. Can you do a rebase and see if that changes what's in this PR?

**Comment by arnoldboy123** [comment]
I have done a git rebase before checking out this branch so I am not really sure why the previous commits in other branches are present here. I tried doing a rebase again and it says that my branch is up to date.

**Comment by arnoldboy123** [comment]
I have now manually resolved the merge conflict in the libraries.md file. Unfortunately that undid some of the changes before. I have made a note of what are the changes I need to do: specifically to change 'my p5.js examples' to just 'p5.js examples'.

For some reason I can't make those changes right now as GitHub will mark it as a merge conflict.

**Review by KevinWorkman — APPROVED** [review]

**Pull request merged**
